language: python
python:
- '2.7'
install:
- cd backend/
- pip install -r requirements.txt
- pip install coveralls
script:
  coverage run --source=app ./test.py
after_success:
  coveralls
notifications:
  email: false
